swagger: "2.0"
info:
  description: Demo project for spring rest docs
  version: 0.0.1-SNAPSHOT
  title: spring-rest-docs
host: localhost
tags: []
schemes:
- http
paths:
  /customers:
    get:
      tags:
      - customers
      summary: The customers resource
      description: The customers resource
      operationId: getCustomers
      produces:
      - application/json
      parameters:
      - name: X-AUTH-TOKEN
        in: header
        description: The authentication token
        required: true
        type: string
      responses:
        "200":
          description: ""
          examples:
            application/json: |-
              [ {
                "customerId" : "87d062f6-fff1-4773-ac3c-adfef04efef1",
                "firstName" : "John",
                "lastName" : "Doe",
                "email" : "john.doe@gmail.com",
                "phone" : "1234567890"
              }, {
                "customerId" : "d16caf50-512f-42d7-a60d-582436013267",
                "firstName" : "Jane",
                "lastName" : "Doe",
                "email" : "jane.doe@gmail.com",
                "phone" : "1234567891"
              } ]
          schema:
            $ref: '#/definitions/Customers.Customer'
definitions:
  Customers.Customer:
    type: array
    items:
      type: object
      properties:
        lastName:
          type: string
          description: The last name of the customer
        firstName:
          type: string
          description: The first name of the customer
        phone:
          type: string
          description: The phone of the customer
        customerId:
          type: string
          description: The id of the customer
        email:
          type: string
          description: The email of the customer
      required:
      - customerId
      - email
      - firstName
      - lastName
      - phone
