openapi: 3.0.1
info:
  title: spring-rest-docs
  description: Demo project for spring rest docs
  version: 0.0.1-SNAPSHOT
servers:
- url: http://localhost
tags: []
paths:
  /customers:
    get:
      tags:
      - customers
      summary: The customers resource
      description: The customers resource
      operationId: getCustomers
      parameters:
      - name: X-AUTH-TOKEN
        in: header
        description: The authentication token
        required: true
        schema:
          type: string
        example: "1234"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customers.Customer'
              examples:
                getCustomers:
                  value: |-
                    [ {
                      "customerId" : "87d062f6-fff1-4773-ac3c-adfef04efef1",
                      "firstName" : "John",
                      "lastName" : "Doe",
                      "email" : "john.doe@gmail.com",
                      "phone" : "1234567890"
                    }, {
                      "customerId" : "d16caf50-512f-42d7-a60d-582436013267",
                      "firstName" : "Jane",
                      "lastName" : "Doe",
                      "email" : "jane.doe@gmail.com",
                      "phone" : "1234567891"
                    } ]
components:
  schemas:
    Customers.Customer:
      title: Customers.Customer
      type: array
      items:
        required:
        - customerId
        - email
        - firstName
        - lastName
        - phone
        type: object
        properties:
          lastName:
            type: string
            description: The last name of the customer
          firstName:
            type: string
            description: The first name of the customer
          phone:
            type: string
            description: The phone of the customer
          customerId:
            type: string
            description: The id of the customer
          email:
            type: string
            description: The email of the customer
